{% set python_min = '3.10' %}
{% set name = "sp-repo-review" %}
{% set version = "2024.08.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/scientific-python/cookie/archive/refs/tags/{{ version }}.tar.gz
  sha256: c73ce95ec5c136a86f0101abb7821ea46c4f938c61a8b796153d8ad8a0eab7b6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv
  number: 1

requirements:
  host:
    - hatchling
    - hatch-fancy-pypi-readme
    - hatch-vcs
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - pyyaml
    - repo-review
    - rich-click

test:
  imports:
    - sp_repo_review
    - sp_repo_review.checks
    - sp_repo_review.families
  source_files:
    - docs
    - tests
    - README.md
    - LICENSE
    - noxfile.py
    - pyproject.toml
    - .github
    - .pre-commit-config.yaml
    - .readthedocs.yaml
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  commands:
    - pip check
    - pytest
    - repo-review --list-all

about:
  home: https://github.com/scientific-python/cookie
  summary: 'A copier/cookiecutter template for new Python projects based on the Scientific Python Developer Guide'
  description: |
    A copier/cookiecutter template for new Python projects based on the Scientific Python Developer Guide.
    What makes this different from other templates for Python packages?
      Lives with the Scientific-Python Development Guide: Every decision is clearly documented and every tool described, and everything is kept in sync.
      Eleven different backends to choose from for building packages.
      Optional VCS versioning for most backends.
      Template generation tested in GitHub Actions using nox.
      Supports generation with copier, cookiecutter, and cruft.
      Supports GitHub Actions if targeting a github.com url (the default), and adds experimental GitLab CI support otherwise.
      Includes several compiled backends using pybind11, with wheels produced for all platforms using cibuildwheel.
      Provides sp-repo-review to evaluate existing repos against the guidelines, with a WebAssembly version integrated with the guide. All checks cross-linked.
      Follows PyPA best practices and regularly updated.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://learn.scientific-python.org/development

extra:
  recipe-maintainers:
    - henryiii
    - MementoRC
