schema_version: 1

context:
  python_min: '3.10'
  name: sp-repo-review
  version: "2025.10.01"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/scientific-python/cookie/archive/refs/tags/${{ version }}.tar.gz
  sha256: bfcab6122345b8cfd330e620a43d24a3332ba07fb8d920dff8706be84f982c0e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - hatchling
    - hatch-fancy-pypi-readme
    - hatch-vcs
    - pip
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}
    - pyyaml
    - repo-review
    - rich-click

tests:
  - python:
      imports:
        - sp_repo_review
        - sp_repo_review.checks
        - sp_repo_review.families
      pip_check: true
      python_version: ${{ python_min }}.*
  - files:
      source:
        - docs/
        - tests/
        - README.md
        - LICENSE
        - noxfile.py
        - pyproject.toml
        - .github/
        - .pre-commit-config.yaml
        - .readthedocs.yaml
    requirements:
      run:
        - pip
        - pytest
        - python ${{ python_min }}.*
    script:
      - pytest
      - repo-review --list-all

about:
  summary: A copier/cookiecutter template for new Python projects based on the Scientific Python Developer Guide
  description: |
    A copier/cookiecutter template for new Python projects based on the Scientific Python Developer Guide.
    What makes this different from other templates for Python packages?
    Lives with the Scientific-Python Development Guide: Every decision is clearly documented and every tool described, and everything is kept in sync.
    Eleven different backends to choose from for building packages.
    Optional VCS versioning for most backends.
    Template generation tested in GitHub Actions using nox.
    Supports generation with copier, cookiecutter, and cruft.
    Supports GitHub Actions if targeting a github.com url (the default), and adds experimental GitLab CI support otherwise.
    Includes several compiled backends using pybind11, with wheels produced for all platforms using cibuildwheel.
    Provides sp-repo-review to evaluate existing repos against the guidelines, with a WebAssembly version integrated with the guide. All checks cross-linked.
    Follows PyPA best practices and regularly updated.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/scientific-python/cookie
  documentation: https://learn.scientific-python.org/development

extra:
  recipe-maintainers:
    - henryiii
    - MementoRC
